import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./styles.css";
import Navbar from './Navbar';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <Navbar />
        {children}

        <footer className="footer">
          <div className="footerLinks">
            <a href="https://www.instagram.com/villanovabelles/">
              <img
                src='/images/instalogo.png'
                alt="Instagram"
                width="28"
                height="28"
              />
              </a>
            <a
              href="mailto:kkoslow@villanova.edu"
              className="footerIconLink"
            >
              <img
                src="/images/emaillogo.png"
                alt="Email"
                width="28"
                height="28"
              />
            </a>

          </div>
        </footer>
      </body>
       

    </html>
  );
}
